---
title: "CUSUM chart"
output: html_document
date: "2024-10-27"
---
```{r}
setClass("CUSUM", representation(upper_signal = "numeric",
                                 lower_signal = "numeric",
                                 CL = "numeric",
                                 x = "numeric",
                                 time = "numeric",
                                 stopped = "logical",
                                 delta = "numeric",
                                 random_time = "numeric"))

setMethod("initialize", "CUSUM", function(.Object, upper_signal, lower_signal, CL, x, time, stopped, delta) {
  upper_signal <- numeric()
  lower_signal <- numeric()
  x <- numeric()
  time <- numeric()
  random_time <- numeric()
  .Object <- callNextMethod(.Object, x=x, upper_signal=upper_signal, lower_signal=lower_signal, CL=CL, time=time, delta=delta)
  return(.Object)
})
```

creator
```{r}
setGeneric("creator", function(object) { standardGeneric("creator")  })
setMethod("creator", signature = "CUSUM", function(object) {
    
  object@random_time <- as.integer(runif(1, 0, 100))
  
  object@stopped = FALSE
  
  object@time = 1 
  
  while (object@time < object@random_time & !object@stopped) {
    
    object@x[object@time] <- rnorm(1)
    
    object <- signals(object)
    
    object <- update(object)
   
  }
  
  while (!object@stopped) {
    
    object@x[object@time] <- rnorm(1,object@delta,1)
    
    object <- signals(object)
    
    object <- update(object)
  }
  
  return(object)

})
```

signals
```{r}
setGeneric("signals", function(object) { standardGeneric("signals")  })
setMethod("signals", signature = "CUSUM", function(object) {
  
  object@upper_signal[object@time] <- max(0, object@upper_signal[object@time - 1] + object@x[object@time] - 0.5)
  
  object@lower_signal[object@time] <- min(0, object@lower_signal[object@time - 1] + object@x[object@time] + 0.5)
  
  return(object)
})
```

update
```{r}
setGeneric("update", function(object) { standardGeneric("update")  })
setMethod("update", signature = "CUSUM", function(object) {
  
  object@time <- object@time + 1
  
  if (length(object@upper_signal) > 0) {
    object@stopped <- (tail(object@upper_signal, 1) > object@CL) || ((tail(object@lower_signal, 1)) < -object@CL)
  }
  
  if (length(object@lower_signal) > 0 ) {
    object@stopped <- (tail(object@upper_signal, 1) > object@CL) || ((tail(object@lower_signal, 1)) < -object@CL)
  }

  return(object)
})
```

show method 
```{r}
setMethod("show", signature = "CUSUM", function(object) {
  # Ensure plot uses length of time sequence, matching signals array lengths
  plot(seq_along(object@upper_signal), object@upper_signal, type = "l", col = "blue",
       ylab = "Signal", xlab = "Time", main = "Upper and Lower Signals Over Time",
       ylim = range(c(object@upper_signal, object@lower_signal, object@CL, -object@CL)))
  
  lines(seq_along(object@lower_signal), object@lower_signal, col = "red")
  
  abline(h = object@CL, col = "green", lty = 2)
  abline(h = -object@CL, col = "orange", lty = 2)
  
  if (!is.na(object@random_time) && object@random_time <= length(object@upper_signal)) {
    abline(v = object@random_time, col = "pink", lty = 2)
  }
  
  # Display textual information
  cat("Data stream display\n")
  cat("Control limit reached at time =", tail(object@time, 1), "\n")
  cat("Mean changed at time =", object@random_time, "\n")
  cat("Absolute value control limit:", object@CL, "\n")
  cat("Last five upper limits:", tail(object@upper_signal, 5), "\n")
  cat("Last five lower limits:", tail(object@lower_signal, 5), "\n")
})
```

call
```{r}
object <- new("CUSUM", upper_signal=upper_signal, lower_signal=lower_signal, 
              CL= spc::xcusum.crit(k = .5, L0 = 370.0, mu0 = 0, hs = 0, sided = "two",r = 30), time=time, delta=1)

show(creator(object))
```

run 10000 simulation without mean change, plot histogram of stopping times, mean of stopping times 
new creator for this purpose 
```{r}
setGeneric("creator2", function(object) {standardGeneric("creator2")})
setMethod("creator2", signature = "CUSUM", function(object) {
  
  object@upper_signal = 0 
  object@lower_signal = 0
  object@stopped = FALSE
  object@time = 1 
  
  while (!object@stopped) {
    
    object@x[object@time] <- rnorm(1)
    
    object <- signals(object)
    
    object <- update(object)
   
  }

  return(object)
})
```
```{r}
stoptime <- numeric(10000)
for (i in 1:10000) {
 object <- creator2(object)
 stoptime[i] <- tail(object@time,1)
}

hist(stoptime, breaks = 50, main = "Histogram of Stopping Times", xlab = "Stopping Time", col = "lightblue")
summary(stoptime)
```




